//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckOnWorkTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckOnWorkTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旷工.
        /// </summary>
        internal static string absent {
            get {
                return ResourceManager.GetString("absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年休假.
        /// </summary>
        internal static string annualLeave {
            get {
                return ResourceManager.GetString("annualLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考勤工具.
        /// </summary>
        internal static string applicationName {
            get {
                return ResourceManager.GetString("applicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考勤.
        /// </summary>
        internal static string checkOnWork {
            get {
                return ResourceManager.GetString("checkOnWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 迟到.
        /// </summary>
        internal static string delay {
            get {
                return ResourceManager.GetString("delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 早退.
        /// </summary>
        internal static string leaveEarly {
            get {
                return ResourceManager.GetString("leaveEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缺卡.
        /// </summary>
        internal static string moCard {
            get {
                return ResourceManager.GetString("moCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月度考勤表：.
        /// </summary>
        internal static string monthlyLb {
            get {
                return ResourceManager.GetString("monthlyLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未打卡.
        /// </summary>
        internal static string noClock {
            get {
                return ResourceManager.GetString("noClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常.
        /// </summary>
        internal static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 签到.
        /// </summary>
        internal static string sign {
            get {
                return ResourceManager.GetString("sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始导出.
        /// </summary>
        internal static string startOutput {
            get {
                return ResourceManager.GetString("startOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外勤.
        /// </summary>
        internal static string waiqin {
            get {
                return ResourceManager.GetString("waiqin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出文件位置：.
        /// </summary>
        internal static string writeExcelLb {
            get {
                return ResourceManager.GetString("writeExcelLb", resourceCulture);
            }
        }
    }
}
